### ISSUE TITLE
Error of adding repo for fedora

### ISSUE THREAD

**Issue by shenwei356** [neufeld/pandaseq#43]
sudo yum-config-manager --add-repo http://neufeldserver.uwaterloo.ca/~apmasell/pandaseq-rpms && sudo yum install pandaseq

Error:

    Bad id for repo: neufeldserver.uwaterloo.ca_~apmasell_pandaseq-rpms, byte = ~ 27

**Comment by apmasell** [comment]
I think this is due to the repository name having invalid characters. In `/etc/yum.repos.d/`, try changing the repository configuration from `[neufeldserver.uwaterloo.ca_~apmasell_pandaseq-rpms]` to `[pandaseq]`.

**Comment by shenwei356** [comment]
Solved. Thanks you @apmasell .
