### ISSUE TITLE
pre-compiled binaries

### ISSUE THREAD

**Issue by mlovci** [neufeld/pandaseq#48]
Are the pre-compiled binaries for x64 linux available for download (without sudo)?

**Comment by apmasell** [comment]
Not really. You can download the Ubuntu packages from http://ppa.launchpad.net/neufeldlab/ppa/ubuntu/pool/main/p/pandaseq/ and unpack them into a directory. You will have to adjust your `PATH` to point to the unpacked `bin` directory and the `LD_LIBRARY_PATH` to point to the `lib` directory.

**Comment by mlovci** [comment]
thanks
