### ISSUE TITLE
libpandaseq.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by audy** [neufeld/pandaseq#52]
Hi, I'm getting the following error when building/installing pandaseq on fresh Ubuntu 14.04:

My build/installation script:

```sh
sudo apt-get update

sudo apt-get install -y git
sudo apt-get install -y build-essential libtool automake zlib1g-dev libbz2-dev pkg-config

git clone https://github.com/neufeld/pandaseq.git pandaseq
cd pandaseq && git checkout v2.8.1

./autogen.sh && ./configure && sudo make install
```

The error:

```
$ pandaseq

pandaseq: error while loading shared libraries: libpandaseq.so.6: cannot open shared object file: No such file or directory.
```

Any help would be appreciated.

**Comment by apmasell** [comment]
First, try running `sudo ldconfig`. If that doesn't work, it usually means there is a version of PANDAseq installed. Try doing `dpkg -l '*pandaseq*'` to look for any errant packages.

**Comment by audy** [comment]
`sudo ldconfig` gives me an unable to resolve host error. `dpkg` finds no packages. I'm building this on a fresh Ubuntu VM.

**Comment by apmasell** [comment]
If `sudo` is failing, that's a problem in general. It generally means the system's network configuration is incorrect. You'll need to run `ldconfig` as root. How did `sudo make install` work?

**Comment by audy** [comment]
Actually, `sudo` isn't failing. It's just printing out that error because my hostname changed for some reason (running this on aws. aws has been weird all morning). I fixed the error and `sudo ldconfig` prints nothing.

**Comment by apmasell** [comment]
`ldconfig` prints nothing if successful. It updates the library cache. Try running `pandaseq` again.

**Comment by audy** [comment]
That worked! :smile_cat:

Does this count as a bug?

**Comment by apmasell** [comment]
Running `sudo ldconfig` is in the installation instructions already.

**Comment by audy** [comment]
oh. *facepalm*

**Comment by audy** [comment]
thanks, by the way :)

**Comment by apmasell** [comment]
No problem. I'm glad it works.
