### ISSUE TITLE
Error with customized sequence labels

### ISSUE THREAD

**Issue by ZeweiSong** [neufeld/pandaseq#53]
I have my read1 and read2 file renamed, so they contain exact  sequence label, but not the original Illumina tag, then I got this error message from Pandaseq:

   ERR	BADID	run1-110-1-1_0:0::0:0:0:0:	run1-110-1-1_0
   * * * * * Something is wrong with this ID. If tags are absent, try passing the -B option.
   * * * * * Consult `pandaseq-checkid "run1-110-1-1_0"` to get an idea of the problem..

I've already include the "-B" option, is there any way to get around of it? Thanks!

**Comment by apmasell** [comment]
This is not supported. Please use original Illumina tag.
