### ISSUE TITLE
What happens when there is high overlap ?

### ISSUE THREAD

**Issue by xapple** [neufeld/pandaseq#54]
I was wondering what happens, when instead of the usual case:

<img width="772" alt="small_overlap" src="https://cloud.githubusercontent.com/assets/649288/15270540/9f308db4-1a23-11e6-8e2b-dd567c2777d2.png">

We have high overlap, going over each of the primers. What does pandseq do ?

<img width="777" alt="high_overlap" src="https://cloud.githubusercontent.com/assets/649288/15270544/aa40d4fc-1a23-11e6-85b0-fdec8c32f17c.png">

I have a dataset like that, where the distance between the two primers is shorter than the read length.

**Comment by apmasell** [comment]
This has been fixed. It will reconstruct the entire sequence, but stop at the forward and reverse primers.

**Comment by xapple** [comment]
OK that's good to know. Is it fixed in the master branch, or is Version 2.8 ok already ?

**Comment by apmasell** [comment]
It's been fixed in 2.8 and later.

**Comment by xapple** [comment]
Thanks, good to know.

**Comment by yech1990** [comment]
It is named as "readthough". The tool, trimomatic can do this well.

**Comment by xapple** [comment]
So you mean you have to activate a special option on the command line ?

**Comment by xapple** [comment]
I didn't find the word "readthough" in the pandaseq documentation.

**Comment by apmasell** [comment]
PANDAseq doesn't require any command line options to deal with this. I believe @yech1990 is referring to the “trimomatic” software package.

**Comment by xapple** [comment]
I just tried it on one sample of my dataset. Primers are 967F and 1046R. So the peak should be around 120. But look at the output from pandaseq. Seems like it finds a much shorter overlap optimal in most cases:

[assembled_len_dist.pdf](https://github.com/neufeld/pandaseq/files/265296/assembled_len_dist.pdf)

**Comment by xapple** [comment]
Ah sorry github only supports displaying PNG not PDF:

![assembled_len_dist](https://cloud.githubusercontent.com/assets/649288/15277055/6d80db58-1af9-11e6-9656-7e4b8ea80082.png)

**Comment by xapple** [comment]
The reads are 111 base pairs each, so a final sequence length of 220 sequences means that pandaseq chose to only make 2 base pairs overlap...

**Comment by apmasell** [comment]
That might be true anyway if the sequences are repetitive. See if increasing the k-mer table to 4 (`-k 4`) improves the situation or try increasing the minimum overlap (`-o 20`).

**Comment by xapple** [comment]
Your suggestions did not work, instead of assembling more reads it just threw them away. Here:

    minimum_overlap = 40
    kmer_table_size = 4

![assembled_len_dist](https://cloud.githubusercontent.com/assets/649288/15277305/a644b750-1b00-11e6-8ca3-60a4641cb88a.png)

**Comment by xapple** [comment]
It took much longer on one core, but I used the default command of mothur:

    mothur > make.contigs(ffastq=fwd.fastq, rfastq=rev.fastq)

And look at the result ! I think I'm going to go with that. Pity, I thought PANDAseq would be the more powerful option.

![assembled_len_dist](https://cloud.githubusercontent.com/assets/649288/15277477/057e2efe-1b06-11e6-9d4f-71ab04adc445.png)
