### ISSUE TITLE
Add release for version 2.9

### ISSUE THREAD

**Issue by mdehollander** [neufeld/pandaseq#55]
Hi @apmasell and @jdneufeld,

Would it be possible to make a release tag for the 2.9 release of july 2015? I see that latest 'official' release on github is version 2.8 but in the commits version 2.9 is mentioned. This would make it easier to install it and make a bio-conda package.

Thanks!

**Comment by apmasell** [comment]
Okay.

**Comment by mdehollander** [comment]
Thanks!
