### ISSUE TITLE
Push Autogenerated Man Page Content and Build Dependancies To S3

### ISSUE THREAD

**Issue by LeeBergstrand** [neufeld/pandaseq#61]
Problem Description:

The pandaseq repo requires several pieces of external content which is currently hosted on ```neufleldserver```. However, this server will be inaccessible in the near future.

Please refer to this closed pull request for more context 

The following pieces of content need to be moved:

- Autogenerated man page (based on CLI man page).
- Vala Docs
- Windows Build Dependancies (For Travis CI Builds)

Problem Solution:

> I think all the VAPI documentation can be deleted rather than saved. If a user wants it, they can regenerate it locally.

> The man page should say, but generated content doesn't belong in git. Can we set up an S3 bucket to hold that content and the Travis build process and dump a copy of the HTML-ified man page there? I did this for a different project: BoutrosLaboratory/bamql@933666e

*TODO:*

- [ ] Generate HTML manpage in TravisCi and push to AWS S3 (See BoutrosLaboratory/bamql@933666e).
- [ ] Delete link to VAPI documentation in Readme
- [ ] Store Windows Build Dependancies on AWS S3 (For Travis CI Builds)

**Comment by LeeBergstrand** [comment]
@apmasell Did I miss anything? and How do I help?

**Comment by apmasell** [comment]
That looks like everything. You and Josh will both have to get an AWS bucket with shared custody. You can create a user/IAM for Travis. The Windows dependency archive can get uploaded manually. For the man page, here's the instructions for setting up the keys: https://docs.travis-ci.com/user/deployment/s3/

I'm not sure if you want to have a UW domain name connected with the bucket (it's not required), but you'll have to get IST to setup a CNAME for you. Create a bucket with the name you want first and it will give the correct address to point the CNAME and then ask IST.

**Comment by LeeBergstrand** [comment]
@apmasell I have the AWS account set up. I was wondering if you want an IAM account I case you need to tweak things? If so I'll send you an email invite.

**Comment by apmasell** [comment]
Sure. That's good.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/neufeld/pandaseq/pull/69
