### ISSUE TITLE
ltld required, install libtool library

### ISSUE THREAD

**Issue by firewater** [neufeld/pandaseq#62]
Hi, I'm trying to install PandaSeq as a non-administrator on a Red Hat server but the compiler is returning the following error:

```
...
checking ltdl.h usability... no
checking ltdl.h presence... no
checking for ltdl.h... no
configure: error: *** ltld required, install libtool library.
```

So I verified all the dependencies are installed:

```
whereis libtool : /usr/bin/libtool /usr/share/libtool
whereis zlib : /usr/include/zlib.h /usr/local/zlib /usr/share/man/man3/zlib.3.gz
whereis libbz2 : /usr/lib64/libbz2.so
whereis bzip2 : /usr/bin/bzip2 /usr/local/bzip2 /usr/share/man/man1/bzip2.1.gz
```

The compiler commands I'm using are:

```
git clone http://github.com/neufeld/pandaseq.git/
cd pandaseq
./autogen.sh
./configure --prefix=/my/dir
```

Any ideas how to make the compiler see `libtool` ?

Thanks!

**Comment by apmasell** [comment]
It is probably seeing `libtool`. It also needs `libltdl` which is part of `libtool`, but packaged into a separate RPM called `libltdl-devel` normally. I'm not sure what the package would be without knowing the version of Red Hat.

**Comment by apmasell** [comment]
It can also be `libtool-ltdl-devel`.

**Comment by firewater** [comment]
Thanks for the quick reply!

So I went ahead and manually downloaded `libtool` and placed it into the pandaseq directory. Within `pandaseq/libtool/libltdl` I see:

```
configure.ac
libltdl (directory)
loaders (directory)
lt__alloc.c
lt__argz.c
lt__dirent.c
ltdl.c
ltdl.h
lt_dlloader.c
ltdl.mk
lt_error.c
lt__strl.c
README
slist.c
```
...and within the libltdl sub-directory, I see:

```
lt__alloc.h
lt__argz_.h
lt__dirent.h
lt_dlloader.h
lt_error.h
lt__glibc.h
lt__private.h
lt__strl.h
lt_system.h
slist.h
```

**Comment by apmasell** [comment]
Dropping it in as a subdirectory won't help.

You're going to have to install `libtool` somewhere you can write to using the `--prefix` option when you configure. You can add that directory + `/bin` directory to `PATH` and set up the LTDL variables as:

    export LTDL_CFLAGS=-I/path/to/libtool/installation/include
    export LTDL_LIBS="-L/path/to/libtool/installation/lib -lltdl"

Then you should be able to configure PANDAseq.

**Comment by firewater** [comment]
Thanks again for the quick reply. In the end, our server administrator installed the following packages which resulted in a successful installation of PANDAseq:

libtool-ltdl-2.2.6-15.5.el6.x86_64
libtool-2.2.6-15.5.el6.x86_64
libtool-ltdl-devel-2.2.6-15.5.el6.x86_64

The PANDA is happy now :)
