### ISSUE TITLE
Installing pandaseq

### ISSUE THREAD

**Issue by mnk2017** [neufeld/pandaseq#63]
Hi,

I am trying to install pandaseq manually and I was wondering if there are more dependencies than what's listed on the manual page.  I've installed libtool successfully and it's in the right place in in my $PATH.

>which libtool
~/PublicProgramFiles/libtool/bin/libtool

When I try to install pandaseq via the manual instructions, I found I needed autoconf and automake packages to be installed, which cleared up one series of error messages.  But my most recent installation attempts are still failing with the message below.  Any help on where to go from here is appreciated!

>./autogen.sh

Makefile.am:4: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:4:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:4:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:4:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:4:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

In case it's helpful:
>automake --version
1.15.1
>autoconf --version
2.6.9
>libtool --version
2.4.6

**Comment by apmasell** [comment]
There are components that are part of `libtool` beyond the executable. Look in the directory for `.m4` files; they should be in `~/PublicProgramFiles/libtool/share/aclocal`. Then, instead of `autogen.sh`, call `autoreconf -i -I ~/PublicProgramFiles/libtool/share/aclocal`.

**Comment by mnk2017** [comment]
Thank you!!  You are right, all the *.m4 files are where you suspected.  I tried the command and got a different error

>autoreconf -i -I ~/PublicProgramFiles/libtool/share/aclocal
autoreconf: 'configure.ac' or 'configure.in' is required

**Comment by apmasell** [comment]
Hmm. Try `autoreconf -i -I ~/PublicProgramFiles/libtool/share/aclocal -I .`

**Comment by mnk2017** [comment]
Thanks I gave it a try, but it seemed to just throw a syntax error
>autoreconf -i -I ~/PublicProgramFiles/libtool/share/aclocal -I
autoreconf: option '-I' requires an argument
autoreconf: Try '/home/PublicProgramFiles/autoconf/bin/autoreconf --help' for more information

I'm fairly new to unix and to me the autoreconf help documentation doesn't seem too helpful.

**Comment by mnk2017** [comment]
I did some more googling with your suggestions as clues.  Though I don't understand why this works, I seemed to make some progress doing the following:

In the pandaseq directory I ran "libtoolize" then ./autogen.sh ran without error.  I'm now running into trouble at the ./configure.  An error is thrown and the make file isn't created.  I've copied below the specific sequence of commands I used.  Any help is appreciated!


>cd /home/PublicProgramFiles/pandaseq-master
>libtoolize
>./autgen.sh
>./configure --prefix=/home/PublicProgramFiles/pandaseq

...lots of output but at the end an error is thrown and the make file isn't made

checking whether uname(2) is POSIX... yes
checking for sys/param.h... yes
checking for sys/sysctl.h... yes
./configure: line 13170: syntax error near unexpected token `Z,'
./configure: line 13170: `PKG_CHECK_MODULES(Z,  zlib )'
[mnahas@researchmaster pandaseq-master]$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by apmasell** [comment]
That means that `pkg-config` is not installed or it's M4 files are not included.

**Comment by mnk2017** [comment]
Hi,

I've tried for last several days to get the install right.  I don't have root privileges and can't run yum so I have to do the whole install manually.  I've installed from scratch m4, autoconf, automake, libtool, zlib, pkg-config and then pandaseq (in that order).  I'm getting the same error.  I've copied and pasted the exact sequence of install commands in case you can spot something.  On my previous issue 4 days ago I hadn't set the PKG_CONFIG_PATH.  Now with it set the zlib package seems to be part of pkg-config libraries:  

> pkg-config zlib --libs
 -L/home/PublicProgramFiles/zlib/lib -lz

But I still am getting the same error when I run ./configure:

./configure: line 13170: syntax error near unexpected token Z,' ./configure: line 13170:PKG_CHECK_MODULES(Z, zlib )'

Exact sequence of install commands.  (but I've cut out the updates of my .bashrc $PATH after each install):

>cd m4-1.4.18
>./configure --prefix="/home/PublicProgramFiles/m4"
>make
>make install

>cd autoconf-2.69
>./configure --prefix=/home/PublicProgramFiles/autoconf
>make
>make install

>cd automake-1.15.1
>./configure --prefix="/home/PublicProgramFiles/automake"
>make
>make install

>cd libtool-2.4.6
>./configure --prefix="/home/PublicProgramFiles/libtool"
>make
>make install

>cd pkg-config-0.28
>./configure --prefix=/home/PublicProgramFiles/pkg-config --with-internal-glib
>make
>make install

>export PKG_CONFIG_PATH=/home/PublicProgramFiles/zlib/lib/pkgconfig/

> pkg-config zlib --libs
 -L/home/PublicProgramFiles/zlib/lib -lz

>cd pandaseq-master
>./autogen
>libtoolize
>./configure --prefix=/home/PublicProgramFiles/panadaseq
 ERROR:
./configure: line 13170: syntax error near unexpected token Z,' ./configure: line 13170:PKG_CHECK_MODULES(Z, zlib )'

**Comment by apmasell** [comment]
pkgconfig also provides M4 files that has to be discoverable. The way you have installed these packages is very non-standard and I'm not surprised they aren't working. You've not set the `PATH` variable, so it is likely that none of your installed programs are even being found. The `PKG_CHECK_MODULES` is a symptom of being unable to find the pkg-config M4 files, not the pkg-config executable.

I'm really not sure how to help you at this point. Your environment is very unusual. You're probably better off using something like [Linuxbrew](http://linuxbrew.sh/) to install the packages. There's a brew recipe for PANDAseq in the [homebrew-science](https://github.com/Homebrew/homebrew-science/blob/master/pandaseq.rb). I've never used homebrew and I don't know how to add repositories, but it will likely be easier than trying to install all the dependencies manually.

**Comment by mnk2017** [comment]
Thanks for the tips.  Sorry I forgot to mention I did modify my PATH variable after every install in .bashrc and then source it so the executables were being found.

I guess I can close this issue, looks like I'm out of luck on getting this installation to work.
