### ISSUE TITLE
pandaseq can't create the output files

### ISSUE THREAD

**Issue by nadiaandreani1** [neufeld/pandaseq#64]
I am trying to use pandaseq to merge paired end reads (unluckily low-quality ones). I found pandaseq easy to use for a non-bioinformatician, as I am.
I am having problems with it as it is frequently crashing. I assume it is not a matter of my input file as:
1.	It is working about 3 times of 10 with files trimmed in the same way
2.	If I run the basic command (pandaseq.exe –f xxx.fastq –r xxx.fastq) there are no problems

However, if I try to create a fastq output file with the option –F, once the “run” is over, my computer can’t create the file. The same is if I use the –g, -W  options.
I think it might be related to my computer, even I thought to have a good machine (4 cores CPUs, 16Gb RAM, 2T hard drive). 
Do you have any suggestion on how to solve this issue? I am sorry if this is a stupid question but I had only a limited bioinformatics experience.

Thanks

**Comment by apmasell** [comment]
1. What do you mean it is working 3 times of 10 files?
1. What errors do you see?
1. What version of Windows and PANDAseq are you using?
1. Have you tried using `pandaseq -f xxx.fastq -r xxx.fastq -w xxx.fasta`?

**Comment by nadiaandreani1** [comment]
I am sorry if my enquiry was not complete.

1.       Of my 38 samples, pandaseq was able to merge the reads of 11, creating the fastq file.

2.       I actually can’t see any error. The command line windows appears as the analysis is still on, a fastq file is created but I can’t use it as it is “incomplete”

3.       I am using windows 7 and pandaseq 2.11

4.       I have just tried using pandaseq -f xxx.fastq -r xxx.fastq -w xxx.fasta: the run ends in the same way (but in this case I can open the file with a text editor tool). However, trying –w xxx.fastq I finally had a fastq file! This was true for the 1st sample, but now trying with the 2nd one, pandaseq crashes again.

I frankly can’t find an explanation!
Do you think I can trust the fasta file even if pandaeq seems to be still working?

Thanks

Nadia

**Comment by nadiaandreani1** [comment]
A quick update: the fasta file is not complete, when comparing it with the fastq file created after the run that worked. Specifically 193 reads are missing in the incomplete fasta file.

Nadia

**Comment by apmasell** [comment]
It is likely that those reads could not be assembled. In the information that is printed to the screen, there is a summary of why read pairs could not be assembled (_e.g._, `STAT LOWQ` or `STAT NOALGN`).

If you want a FASTQ file, do `pandaseq -f xxx.fastq -r xxx.fastq -F -w xxx.fastq` but you need to understand that the output quality score are very different from the input quality scores and you should not use them in other tools.

**Comment by nadiaandreani1** [comment]
I actually find it strange that the same 2 input files can give a fastq file as output and not a fasta one. The problem of the fast is that: the analysis doesn’t come to the end and I can’t see the summary.

**Comment by apmasell** [comment]
Please provide a screen shot.

**Comment by nadiaandreani1** [comment]
With –w fasta
[cid:image002.png@01D32AF1.91472480]

With –w fastq

[cid:image001.png@01D32AF2.04334F00]

On Friday, the contrary was happening. It seems a random thing to me. I can’t find an explanation.

N

**Comment by apmasell** [comment]
Those did not display.

**Comment by nadiaandreani1** [comment]
![fasta](https://user-images.githubusercontent.com/31773047/30270774-cb9136a2-96e5-11e7-8096-4d30374f5bbf.png)
![fastq](https://user-images.githubusercontent.com/31773047/30270773-cb8f63d6-96e5-11e7-8653-bf6559fad9cf.png)

**Comment by apmasell** [comment]
Try running it with `-T 1`, please.

**Comment by nadiaandreani1** [comment]
It works!
Both with –T 1 and with –T 1 –F.

I will try a couple of datasets and I will let you know if it is working.

Thanks a lot for the help and the patience!

Nadia
