### ISSUE TITLE
Output quality scores

### ISSUE THREAD

**Issue by pschloss** [neufeld/pandaseq#67]
I'm not sure if I'm missing it somewhere in the options, but is there a way to output the quality score for each sequence? Possibly in the header of the outputted fasta/fastq file? I know the `-t` argument uses a default quality score threshold of 0.6, but it would be nice to see the distribution of the score for each sequence.

**Comment by pschloss** [comment]
Hmmm that doesn't look like fun. would there be an easy way to concatenate the probability to the end of the sequence name at that point in `align`?

**Comment by apmasell** [comment]
In `output.c` in either `panda_output_fasta` or `panda_output_fastq`, you could do:

```
panda_writer_append(writer, " %f", sequence->estimated_overlap_probability);
```
Just after the sequence name.

**Comment by pschloss** [comment]
Thanks -
```
panda_writer_append(writer, " %f", exp(sequence->quality));
```
 would be better for the quality score that is compared to the threshold, right?

**Comment by pschloss** [comment]
Would you be interested in a PR for this?

**Comment by apmasell** [comment]
Sure! Though, I haven't done a release in a long while.
