### ISSUE TITLE
Permission issue with /.libs

### ISSUE THREAD

**Issue by hariszaf** [neufeld/pandaseq#71]
Hi everyone, 

I am trying to run PANDASEQ inside a Singularity container and I get this error: 
```
/usr/bin/ld: cannot open output file /home/tools/PANDAseq/pandaseq/.libs/23668-lt-pandaseq: Permission denied 
collect2: error: ld returned 1 exit status
```

Has anybody any idea what could I do?

Thank,
Haris

**Comment by apmasell** [comment]
I'm not familiar with Singularity, but this looks like it doesn't have write access to the source directory during compilation. Maybe you started compilation outside of the container and restarted it inside the container running as a different user?

**Comment by hariszaf** [comment]
Hi! 
I'm a starter in Singularity as well, however as far as I know, the compilation is done when you make the image and it should be ready to go.. Think that in the Docker image i have made, it works just fine! And when i use this Docker image to create the corresponding Singularity one, I get this error..

**Comment by apmasell** [comment]
Is `/home/tools/PANDAseq/pandaseq/` the compilation directory or was it created with `make install`?

**Comment by hariszaf** [comment]
When I create the image i do this: 

RUN git clone http://github.com/neufeld/pandaseq.git && cd pandaseq && ./autogen.sh && ./configure && make && make install

So, i do use ''make install'' command!

**Comment by apmasell** [comment]
When you do `make install`, this will copy the built packages into `/usr/local`. The copy of the binary that is in that directory is the libtool test artifact and should not be used outside of the build process. If you want to install to another directory, use `./configure --prefix=/path/to/target/directory`.

**Comment by hariszaf** [comment]
Sorry for the delay! 
I think that your answer works nice with me! 
Sorry I never thought before I ask! 
Thanks again!

**Comment by apmasell** [comment]
No po\roblem.
