### ISSUE TITLE
what if both bases in overlapped region have high scores?

### ISSUE THREAD

**Issue by liethan** [neufeld/pandaseq#73]
HI, currently I am going to implement read merging. However, my data show a perplexing problem that there is a significant proportion of read pairs, which both bases in the overlapped  region have very high quality scores? Do you have any ideas for what may cause this kind of proplem?

**Comment by apmasell** [comment]
This is working as designed. Do not use the quality scores in this way. They were not design for this and they do not have uniform meaning.
https://github.com/neufeld/pandaseq#the-scores-of-the-output-bases-seem-really-low-whats-wrong
