### ISSUE TITLE
pandaseq -h   returns 1, should be 0

### ISSUE THREAD

**Issue by tseemann** [neufeld/pandaseq#75]
pandaseq -h
echo $?
1

**Comment by apmasell** [comment]
Working as intended. Requesting help is not a successful status.

**Comment by tseemann** [comment]
I asked for help, you gave it. It was a success.
If i had NOT asked for it, and you printed it out, that would be a failure.

**Comment by apmasell** [comment]
Lots of programs exit non-zero when printing help including `ping`, `fuser`, `sqlite3`, and `xxd`. I think this is a bad change. If a user expects data processing to happen, supplies `-h` by accident, the program should not exit successfully, especially if they're streaming what is normally sequence data off stdout which would now look like an empty file.

**Comment by tseemann** [comment]
I guess we have to agree to disagree on this one. 

None of those are GNU tools, and have legacy (BSD or other) Unix roots from long ago, 1990s.
I note`fuser -V` and `xxd -v` (version) doereturn 0.
