### ISSUE TITLE
pandaseq now in brew

### ISSUE THREAD

**Issue by tseemann** [neufeld/pandaseq#77]
FYI
```
% brew install brewsci/bio/pandaseq
```
works on Mac Homebrew and Linuxbrew
includes citation to your paper.
https://github.com/brewsci/homebrew-bio/pull/801/files

**Comment by apmasell** [comment]
Thanks

**Comment by tseemann** [comment]
Would be great if you could add it to your INSTALL docs.

**Comment by apmasell** [comment]
Please open a PR with the change.

**Comment by tseemann** [comment]
I just spent 30 mins putting the software into Brew to help you and your users, so I decline.
