### ISSUE TITLE
pandaseq error

### ISSUE THREAD

**Issue by lasupernova** [neufeld/pandaseq#78]
I received the following error when trying to run pandaseq

`pandaseq: error while loading shared libraries: libpandaseq.so.7: cannot open shared object file: No such file or directory`

Can you suggest what I am doing wrong?

the command I ran was:

` sudo pandaseq -f PATH_TO_FILE.filt.fastq -r PATH_TO_FILE.filt.fastq`

thanks in advance

**Comment by apmasell** [comment]
How did you install it?

**Comment by lasupernova** [comment]
I installed it based on the installation instruction:

`sudo apt-get install build-essential libtool automake zlib1g-dev libbz2-dev pkg-config`

```
git clone http://github.com/neufeld/pandaseq.git/
cd pandaseq
```
here, I added sudo before every part so that it would work
`sudo ./autogen.sh && sudo ./configure && sudo make && sudo make install`

when I run `man pandaseq` the manual is printed, so I think it must be installed right

**Comment by apmasell** [comment]
It should have install `libpandaseq.so.7` in `/usr/local/lib`. Can you check for that file and also do `which pandaseq`?

**Comment by lasupernova** [comment]
I have the following files in /`usr/local/lib` :

```
libpandaseq.a   libpandaseq.so    libpandaseq.so.7.0.0  pkgconfig  python3.6
libpandaseq.la  libpandaseq.so.7  pandaseq7             python2.7
```

`libpandaseq.so.7` is in the directory 


`which pandaseq `gives me the following output `/usr/local/bin/pandaseq`

**Comment by apmasell** [comment]
Try running `sudo ldconfig` and then try running it again. If it fails, please give me the output of `ldd /usr/local/bin/pandaseq` and `ldconfig -v 2>/dev/null | grep -v ^$'\t'`

**Comment by lasupernova** [comment]
It is running, so `sudo ldconfig` seems to have worked. Thanks a lot!

**Comment by apmasell** [comment]
Great. Normally the install script does that. I'm not sure why that didn't happen.

**Comment by NamLQ** [comment]
> Try running `sudo ldconfig` and then try running it again. If it fails, please give me the output of `ldd /usr/local/bin/pandaseq` and `ldconfig -v 2>/dev/null | grep -v ^$'\t'`

It worked for me also. Thanks!
