### ISSUE TITLE
ERR BADID with mock sample

### ISSUE THREAD

**Issue by cimendes** [neufeld/pandaseq#80]
Hello! I'm trying to use pandaseq to assemble a mock community sample for a [benchmark project](https://github.com/cimendes/LMAS) and i'm running into the following error: 

> NFO    VER     pandaseq 2.11 <andre@masella.name>
> INFO    UNAME   Linux 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64
> ARG[0]  /mnt/beegfs/scratch/ONEIDA/oneida/smallfiles-64k/cimendes/LMAS/work/31/8d3e3886adb16cffebcaf5400c6d68/pandaseq/.libs/lt-pandaseq
> ARG[1]  -T
> ARG[2]  4
> ARG[3]  -w
> ARG[4]  mockSample_pandaseq.fasta
> ARG[5]  -f
> ARG[6]  mockSample_1.fq.gz
> ARG[7]  -r
> ARG[8]  mockSample_2.fq.gz
> ARG[9]  -B
> STAT    THREADS 4
> 0x150f610:2     STAT    TIME    Mon Dec  7 18:30:47 2020
> 0x150f610:2     STAT    ELAPSED 0
> 0x150f610:2     STAT    READS   0
> 0x150f610:2     STAT    NOALGN  0
> 0x150f610:2     STAT    LOWQ    0
> 0x150f610:2     STAT    BADR    0
> 0x150f610:2     STAT    SLOW    0
> 0x150f610:2     STAT    OK      0
> 0x150f610:2     STAT    OVERLAPS        0
> 0x150f610:0     STAT    TIME    Mon Dec  7 18:30:47 2020
> 0x150f610:0     STAT    ELAPSED 0
> 0x150f610:0     STAT    READS   0
> 0x150f610:0     STAT    NOALGN  0
> 0x150f610:0     STAT    LOWQ    0
> 0x150f610:0     STAT    BADR    0
> 0x150f610:0     STAT    SLOW    0
> 0x150f610:0     STAT    OK      0
> 0x150f610:0     STAT    OVERLAPS        0
> 0x150f610:3     STAT    TIME    Mon Dec  7 18:30:47 2020
> 0x150f610:3     STAT    ELAPSED 0
> 0x150f610:3     STAT    READS   0
> 0x150f610:3     STAT    NOALGN  0
> 0x150f610:3     STAT    LOWQ    0
> 0x150f610:3     STAT    BADR    0
> 0x150f610:3     STAT    SLOW    0
> 0x150f610:3     STAT    OK      0
> 0x150f610:3     STAT    OVERLAPS        0
> 0x150f610:1     STAT    TIME    Mon Dec  7 18:30:47 2020
> 0x150f610:1     STAT    ELAPSED 0
> 0x150f610:1     STAT    READS   0
> 0x150f610:1     STAT    NOALGN  0
> 0x150f610:1     STAT    LOWQ    0
> 0x150f610:1     STAT    BADR    0
> 0x150f610:1     STAT    SLOW    0
> 0x150f610:1     STAT    OK      0
> 0x150f610:1     STAT    OVERLAPS        0
> ERR     BADID   Enterococcus_faecalis_complete_genome-305366:::0:0:0:0: Enterococcus_faecalis_complete_genome-305366/1
> * * * * * Something is wrong with this ID. If tags are absent, try passing the -B option.
> * * * * * Consult `pandaseq-checkid "Enterococcus_faecalis_complete_genome-305366/1"` to get an idea of the problem

The dataset is available [here](https://drive.google.com/drive/folders/1gtLvp_k_4arZLV2-SRysj9iMx2tMljRf?usp=sharing) and it works without any issue with the other assemblers in my selection. I'm using pandaseq in this [container](https://hub.docker.com/repository/docker/cimendes/pandaseq), version 2.11, with the [following](https://github.com/cimendes/LMAS/blob/3fc01cfa2b3fa909ecbfd301de14de610604350c/LMAS.nf#L337) command. 

Any assistance with this issue is greatly appreciated!

**Comment by apmasell** [comment]
It seems like you've modified the sample names. PANDAseq expects them to be in the original format produced by CASAVA, the EBI Short Read Archive, or the NCBI Short Read Archive.

You can either change your data to match one of the approved formats or modify `seq_id.c` to parse your custom format. For testing `pandaseq-checkid` will test whether PANDAseq understands the sequence header.

Valid CASAVA headers are:

```
M01271:10:000000000-A3WGH:1:1101:18786:6175 1:N:0:1
ILLUMINA-BE9C3F:29:FC:3:1:2462:1120 1:N:0:GCTATA
M00958:47:000000000-A3GH7:1:1101:15028:1512 2:N:0:3
1468:1:1:12675:1118#ATCACGA/1
1468:1:1:12675:1118#ATCACGA/2
MISEQ03:18:000000000-A1REG:1:1101:14774:1712#GATAGTGCCAC/1
```
