### ISSUE TITLE
How to leave primers and barcodes in the assembly? 

### ISSUE THREAD

**Issue by sd784** [neufeld/pandaseq#82]
Hello! I'm using pandaseq for the first time to assemble Illumina reads. The plan is to then take the merged reads and then demultiplex and bin them according to primer and barcode using a different program. 

I'm trying to find how to specify to pandaseq to maintain the primers and barcodes (instead of the default of cropping them out) but I've been looking through the manual and am not clear on which option to use - I see several options about stripping out primers but none about keeping them. Is there a good option to use to keep primers/barcodes for the output file?

**Comment by apmasell** [comment]
If you don't specify the primer (_i.e._, don't give `-p` and `-q`), PANDAseq will assemble the read without doing any clipping of any kind. PANDAseq never strips barcodes; they are always included in the output header, but the output header is no longer the same as CASAVA's header format.
